# .github/workflows/ci.yml

# 1. Give your workflow a name
name: Continuous Integration

# 2. Define the triggers for this workflow
on:
  push:
    branches: [ "main" ] # Run on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Run on pull requests targeting the main branch

# 3. Define the jobs that will run
jobs:
  # We will have one job, called 'build'
  build:
    # The type of machine to run the job on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # A series of steps that make up the job
    steps:
      # Step 1: Check out your repository's code so the job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a specific version of Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install the project's dependencies
      # It's good practice to upgrade pip first
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the linter
      # This is the actual 'test' for our CI pipeline
      - name: Lint with flake8
        run: |
          flake8 . --count --statistics